### ISSUE TITLE
CLINT address differs from GFE

### ISSUE THREAD

**Issue by jrtc27** [acceleratedtech/ssith-aws-fpga#3]
The GFE puts the CLINT at 0x10000000, whereas https://github.com/acceleratedtech/ssith-aws-fpga/commit/9a35bb2beb937a04ae64e1a438d458e3ce089700 moved it from that to 0x10020000. Is there a good reason for this? I would really like to see this SoC map be as close to the GFE as possible, aside from where we use different devices.

**Comment by jameyhicks** [comment]
It got moved because we had HTIF at 0x10001000 and they overlapped. There was a bit of version skew, because I added a flag to enable moving HTIF while @joestoy updated the SoC_Map.

My plan is for the SoC_Map.bsv in src_AWS_P2 to align with the GFE and for the SoC_Map.bsv in src_AWS_P2_CHERI to be the one from the CHERI Flute repo. See branch 
   https://github.com/acceleratedtech/ssith-aws-fpga/tree/jamey/connect-bluestuff/hw/src_AWS_P2_CHERI
which I was able to compile yesterday.

**Comment by jameyhicks** [comment]
Does FreeBSD use device tree to tell the OS where all the devices are in memory?

**Comment by jrtc27** [comment]
Yes, it does. That's also true of riscv-pk/BBL, but not OpenSBI, though neither the GFE nor CHERI uses OpenSBI. My concern is more that changing the SoC map requires source changes to all the SoC_Map.bsv's, and it would be very easy for our CHERI one that's using BlueStuff to become out of sync.

If we are concerned with where cached DRAM is, however, it really is important that that be the same between the GFE and here. The M-mode boot loader, be it BBL or OpenSBI, is linked for a given physical address; changing where that is causes it to break (or be slow because it's in uncached DRAM), and we really want to be able to build software that runs on both rather than having separate builds. On CHERI it's particularly important, as only cached DRAM is tagged, so the tag controller needs to be configured correctly, and BBL really needs to be running from cached DRAM. But I doubt you intend to change where cached DRAM is, so that's unlikely to be a concern.

**Comment by jameyhicks** [comment]
Well, I did change where cached DRAM was in my variant, but not in the GFE variant.

I expect no changes in the SoC_Map for CHERI Flute.

**Comment by jrtc27** [comment]
So long as the GFE variant looks like the GFE and we align with the GFE variant I'm happy; you're free to do what you want with the MIT core :)

**Comment by joestoy** [comment]
The clint address is the only deviation from the standard GFE map, for the reason @jameyhicks mentioned.  Now that we've replaced the htif by a uart model we can change it back.  I'll do that once the current boot works.

**Comment by jameyhicks** [comment]
I have an AWS image with the same map as GFE. Do you have a FreeBSD+bbl executable I can test?

**Comment by jameyhicks** [comment]
Based on report from jrtc27 that FreeBSD booted, closing this issue.
